//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmSoul.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmSoul.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 聚合查询失败 的本地化字符串。
        /// </summary>
        public static string AggregateFail {
            get {
                return ResourceManager.GetString("AggregateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增失败 的本地化字符串。
        /// </summary>
        public static string CreateFail {
            get {
                return ResourceManager.GetString("CreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增成功 的本地化字符串。
        /// </summary>
        public static string CreateSucceeded {
            get {
                return ResourceManager.GetString("CreateSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败，共删除 {0} 条记录 的本地化字符串。
        /// </summary>
        public static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功，共删除 {0} 条记录 的本地化字符串。
        /// </summary>
        public static string DeleteSucceeded {
            get {
                return ResourceManager.GetString("DeleteSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程异常 的本地化字符串。
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询完成 的本地化字符串。
        /// </summary>
        public static string QueryComplete {
            get {
                return ResourceManager.GetString("QueryComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无匹配记录 的本地化字符串。
        /// </summary>
        public static string QueryFail {
            get {
                return ResourceManager.GetString("QueryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询参数错误 的本地化字符串。
        /// </summary>
        public static string QueryParamError {
            get {
                return ResourceManager.GetString("QueryParamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询到 {0} 条记录 的本地化字符串。
        /// </summary>
        public static string QuerySucceeded {
            get {
                return ResourceManager.GetString("QuerySucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;是必需字段 的本地化字符串。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败，共更新 {0} 条记录 的本地化字符串。
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功，共更新 {0} 条记录 的本地化字符串。
        /// </summary>
        public static string UpdateSucceeded {
            get {
                return ResourceManager.GetString("UpdateSucceeded", resourceCulture);
            }
        }
    }
}
