//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmSoul.Identity.MongoDB {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityErrorResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmSoul.Identity.MongoDB.IdentityErrorResource", typeof(IdentityErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 验证通过 的本地化字符串。
        /// </summary>
        public static string AuthenticationPassed {
            get {
                return ResourceManager.GetString("AuthenticationPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 并发错误，对象已被修改！ 的本地化字符串。
        /// </summary>
        public static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误！ 的本地化字符串。
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 &apos;{0}&apos; 已经存在！ 的本地化字符串。
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名 &apos;{0}&apos; 已经存在！ 的本地化字符串。
        /// </summary>
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 &apos;{0}&apos; 已存在！ 的本地化字符串。
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email不能为空 的本地化字符串。
        /// </summary>
        public static string EmailIsNull {
            get {
                return ResourceManager.GetString("EmailIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化错误 的本地化字符串。
        /// </summary>
        public static string InitializeFail {
            get {
                return ResourceManager.GetString("InitializeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 &apos;{0}&apos; 格式错误！ 的本地化字符串。
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色错误 的本地化字符串。
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 &apos;{0}&apos; 验证错误！ 的本地化字符串。
        /// </summary>
        public static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 令牌无效 的本地化字符串。
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 &apos;{0}&apos; 错误，只可以包含数字和字母！ 的本地化字符串。
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户已经登录！ 的本地化字符串。
        /// </summary>
        public static string LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;不能为 null 或空。 的本地化字符串。
        /// </summary>
        public static string NotAllowedNull {
            get {
                return ResourceManager.GetString("NotAllowedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码修改成功 的本地化字符串。
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码修改失败 的本地化字符串。
        /// </summary>
        public static string PasswordIsNotChanged {
            get {
                return ResourceManager.GetString("PasswordIsNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误！ 的本地化字符串。
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码至少有一个数字 (&apos;0&apos;-&apos;9&apos;). 的本地化字符串。
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码必须包含小写字母 (&apos;a&apos;-&apos;z&apos;). 的本地化字符串。
        /// </summary>
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码必须至少有一个非字母数字字符. 的本地化字符串。
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码必须包含大写字母 (&apos;A&apos;-&apos;Z&apos;). 的本地化字符串。
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码最小长度应当为 {0} ！ 的本地化字符串。
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要密码 的本地化字符串。
        /// </summary>
        public static string RequiresPassword {
            get {
                return ResourceManager.GetString("RequiresPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要&apos;用户名&apos;或&apos;Email&apos;之一 的本地化字符串。
        /// </summary>
        public static string RequiresUserNameOrEmail {
            get {
                return ResourceManager.GetString("RequiresUserNameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增角色 &apos;{0}&apos;成功 的本地化字符串。
        /// </summary>
        public static string RoleCreated {
            get {
                return ResourceManager.GetString("RoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增角色失败 的本地化字符串。
        /// </summary>
        public static string RoleCreateFail {
            get {
                return ResourceManager.GetString("RoleCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已经设置了密码. 的本地化字符串。
        /// </summary>
        public static string UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已已有角色 &apos;{0}&apos; 权限. 的本地化字符串。
        /// </summary>
        public static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增用户&apos;{0}&apos;成功 的本地化字符串。
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增用户失败 的本地化字符串。
        /// </summary>
        public static string UserCreateFail {
            get {
                return ResourceManager.GetString("UserCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        public static string UserDoseNotExit {
            get {
                return ResourceManager.GetString("UserDoseNotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未为此用户启用锁定. 的本地化字符串。
        /// </summary>
        public static string UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        public static string UserNameIsNull {
            get {
                return ResourceManager.GetString("UserNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户没有角色 &apos;{0}&apos; 权限. 的本地化字符串。
        /// </summary>
        public static string UserNotInRole {
            get {
                return ResourceManager.GetString("UserNotInRole", resourceCulture);
            }
        }
    }
}
